# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1346, 813)
        MainWindow.setStyleSheet("background-color: rgb(73, 73, 73);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mensajeBinario = QtWidgets.QRadioButton(self.centralwidget)
        self.mensajeBinario.setGeometry(QtCore.QRect(80, 140, 171, 31))
        self.mensajeBinario.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.mensajeBinario.setObjectName("mensajeBinario")
        self.binarioDecimal = QtWidgets.QRadioButton(self.centralwidget)
        self.binarioDecimal.setGeometry(QtCore.QRect(280, 140, 171, 41))
        self.binarioDecimal.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.binarioDecimal.setObjectName("binarioDecimal")
        self.decimalBinario = QtWidgets.QRadioButton(self.centralwidget)
        self.decimalBinario.setGeometry(QtCore.QRect(480, 150, 171, 31))
        self.decimalBinario.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.decimalBinario.setObjectName("decimalBinario")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 10, 361, 31))
        self.label.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.cuerpoTexto = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.cuerpoTexto.setGeometry(QtCore.QRect(60, 210, 601, 261))
        self.cuerpoTexto.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.cuerpoTexto.setObjectName("cuerpoTexto")
        self.envioCorreos = QtWidgets.QPushButton(self.centralwidget)
        self.envioCorreos.setGeometry(QtCore.QRect(280, 530, 151, 41))
        self.envioCorreos.setStyleSheet("background-color: rgb(0, 255, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.envioCorreos.setObjectName("envioCorreos")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(860, 140, 241, 31))
        self.label_2.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(60, 620, 1231, 141))
        self.plainTextEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabla = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla.setGeometry(QtCore.QRect(710, 210, 601, 261))
        self.tabla.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(4)
        self.tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tabla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tabla.setHorizontalHeaderItem(3, item)
        self.tabla.horizontalHeader().setDefaultSectionSize(149)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1346, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mensajeBinario.setText(_translate("MainWindow", "mensajeBinario"))
        self.binarioDecimal.setText(_translate("MainWindow", "binarioDecimal"))
        self.decimalBinario.setText(_translate("MainWindow", "decimalBinario"))
        self.label.setText(_translate("MainWindow", "Envio De Correos Cifrados"))
        self.envioCorreos.setText(_translate("MainWindow", "Enviar Correo"))
        self.label_2.setText(_translate("MainWindow", "Analisis Sintactico"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "La gramatica nos indica si se puede enviar exitosamente un correo o no. Ejemplo de gramatica correcta:\n"
"\n"
"remitente@gmail.com <P> password <A> mi asunto <D> destinatario@gmail.com <M> mensaje\n"
"\n"
"Una vez teniendo la gramatica se selecciona el tipo de cifrado."))
        item = self.tabla.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tipo De Error"))
        item = self.tabla.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Linea"))
        item = self.tabla.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Posicion"))
        item = self.tabla.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Simbolo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
