
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A ARROBA B BN CARACTERES D DIGITOS DOMINIO GUIONBAJO LETRAS M MB NB P PUNTO T TIPOS : Remitente P Password A Asunto D Destinatario M MensajeRemitente : CorreoAsunto : Letras transformacion\n                | Numeros transformacion\n                | CARACTERES\n                | emptyMensaje : Letras transformacion\n                | Numeros transformacion\n                | CARACTERES\n                | emptyDestinatario : Correo Password : Letras restoPass\n\t\t\t\t| Numeros restoPass\n\t\t\t\t| Caracteres restoPass restoPass : Letras restoPass\n\t\t\t\t| Numeros restoPass\n\t\t\t\t| Caracteres restoPass\n\t\t\t\t| empty Caracteres : CARACTERESCorreo : Usuario ARROBA Dominio PUNTO TipoUsuario : Letras restoID\n                | Numeros restoIDrestoID : Letras restoID\n                | GUIONBAJO restoID\n                | Numeros restoID\n                | PUNTO restoID\n                | empty Dominio : DOMINIO Tipo : TIPO Letras : LETRAS Numeros : DIGITOS transformacion : Letras transformacion\n                | Numeros transformacion\n                | empty empty :'
    
_lr_action_items = {'LETRAS':([0,5,6,7,8,9,11,13,14,15,19,20,21,22,29,30,32,33,39,40,48,49,51,58,60,61,],[7,7,7,-30,-31,7,7,7,7,7,7,7,7,-19,7,7,7,7,7,7,7,7,7,7,7,7,]),'DIGITOS':([0,5,6,7,8,9,11,13,14,15,19,20,21,22,29,30,32,33,39,40,48,49,51,58,60,61,],[8,8,8,-30,-31,8,8,8,8,8,8,8,8,-19,8,8,8,8,8,8,8,8,8,8,8,8,]),'$end':([1,7,8,49,51,52,56,57,58,59,60,61,62,63,64,65,],[0,-30,-31,-35,-35,-34,-32,-33,-35,-1,-35,-35,-9,-10,-7,-8,]),'P':([2,3,46,47,],[9,-2,-20,-29,]),'ARROBA':([4,5,6,7,8,11,12,13,14,15,16,17,25,26,27,28,],[10,-35,-35,-30,-31,-35,-21,-35,-35,-35,-27,-22,-23,-24,-25,-26,]),'GUIONBAJO':([5,6,7,8,11,13,14,15,],[13,13,-30,-31,13,13,13,13,]),'PUNTO':([5,6,7,8,11,13,14,15,23,24,],[15,15,-30,-31,15,15,15,15,37,-28,]),'CARACTERES':([7,8,9,19,20,21,22,29,30,32,33,58,],[-30,-31,22,22,22,22,-19,41,22,22,22,62,]),'A':([7,8,18,19,20,21,22,30,31,32,33,34,35,36,43,44,45,],[-30,-31,29,-35,-35,-35,-19,-35,-12,-35,-35,-18,-13,-14,-15,-16,-17,]),'D':([7,8,29,38,39,40,41,42,49,50,51,52,53,56,57,],[-30,-31,-35,48,-35,-35,-5,-6,-35,-3,-35,-34,-4,-32,-33,]),'DOMINIO':([10,],[24,]),'TIPO':([37,],[47,]),'M':([46,47,54,55,],[-20,-29,58,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'Remitente':([0,],[2,]),'Correo':([0,48,],[3,55,]),'Usuario':([0,48,],[4,4,]),'Letras':([0,5,6,9,11,13,14,15,19,20,21,29,30,32,33,39,40,48,49,51,58,60,61,],[5,11,11,19,11,11,11,11,30,30,30,39,30,30,30,49,49,5,49,49,60,49,49,]),'Numeros':([0,5,6,9,11,13,14,15,19,20,21,29,30,32,33,39,40,48,49,51,58,60,61,],[6,14,14,20,14,14,14,14,32,32,32,40,32,32,32,51,51,6,51,51,61,51,51,]),'restoID':([5,6,11,13,14,15,],[12,17,25,26,27,28,]),'empty':([5,6,11,13,14,15,19,20,21,29,30,32,33,39,40,49,51,58,60,61,],[16,16,16,16,16,16,34,34,34,42,34,34,34,52,52,52,52,63,52,52,]),'Password':([9,],[18,]),'Caracteres':([9,19,20,21,30,32,33,],[21,33,33,33,33,33,33,]),'Dominio':([10,],[23,]),'restoPass':([19,20,21,30,32,33,],[31,35,36,43,44,45,]),'Asunto':([29,],[38,]),'Tipo':([37,],[46,]),'transformacion':([39,40,49,51,60,61,],[50,53,56,57,64,65,]),'Destinatario':([48,],[54,]),'Mensaje':([58,],[59,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> Remitente P Password A Asunto D Destinatario M Mensaje','S',9,'p_S','sintactico.py',6),
  ('Remitente -> Correo','Remitente',1,'p_Remitente','sintactico.py',9),
  ('Asunto -> Letras transformacion','Asunto',2,'p_Asunto','sintactico.py',12),
  ('Asunto -> Numeros transformacion','Asunto',2,'p_Asunto','sintactico.py',13),
  ('Asunto -> CARACTERES','Asunto',1,'p_Asunto','sintactico.py',14),
  ('Asunto -> empty','Asunto',1,'p_Asunto','sintactico.py',15),
  ('Mensaje -> Letras transformacion','Mensaje',2,'p_Mensaje','sintactico.py',19),
  ('Mensaje -> Numeros transformacion','Mensaje',2,'p_Mensaje','sintactico.py',20),
  ('Mensaje -> CARACTERES','Mensaje',1,'p_Mensaje','sintactico.py',21),
  ('Mensaje -> empty','Mensaje',1,'p_Mensaje','sintactico.py',22),
  ('Destinatario -> Correo','Destinatario',1,'p_Destinatario','sintactico.py',25),
  ('Password -> Letras restoPass','Password',2,'p_Password','sintactico.py',28),
  ('Password -> Numeros restoPass','Password',2,'p_Password','sintactico.py',29),
  ('Password -> Caracteres restoPass','Password',2,'p_Password','sintactico.py',30),
  ('restoPass -> Letras restoPass','restoPass',2,'p_restoPass','sintactico.py',35),
  ('restoPass -> Numeros restoPass','restoPass',2,'p_restoPass','sintactico.py',36),
  ('restoPass -> Caracteres restoPass','restoPass',2,'p_restoPass','sintactico.py',37),
  ('restoPass -> empty','restoPass',1,'p_restoPass','sintactico.py',38),
  ('Caracteres -> CARACTERES','Caracteres',1,'p_Caracteres','sintactico.py',41),
  ('Correo -> Usuario ARROBA Dominio PUNTO Tipo','Correo',5,'p_Correo','sintactico.py',44),
  ('Usuario -> Letras restoID','Usuario',2,'p_Usuario','sintactico.py',48),
  ('Usuario -> Numeros restoID','Usuario',2,'p_Usuario','sintactico.py',49),
  ('restoID -> Letras restoID','restoID',2,'p_restoID','sintactico.py',52),
  ('restoID -> GUIONBAJO restoID','restoID',2,'p_restoID','sintactico.py',53),
  ('restoID -> Numeros restoID','restoID',2,'p_restoID','sintactico.py',54),
  ('restoID -> PUNTO restoID','restoID',2,'p_restoID','sintactico.py',55),
  ('restoID -> empty','restoID',1,'p_restoID','sintactico.py',56),
  ('Dominio -> DOMINIO','Dominio',1,'p_Dominio','sintactico.py',59),
  ('Tipo -> TIPO','Tipo',1,'p_Tipo','sintactico.py',62),
  ('Letras -> LETRAS','Letras',1,'p_Letras','sintactico.py',65),
  ('Numeros -> DIGITOS','Numeros',1,'p_Numeros','sintactico.py',68),
  ('transformacion -> Letras transformacion','transformacion',2,'p_transformacion','sintactico.py',71),
  ('transformacion -> Numeros transformacion','transformacion',2,'p_transformacion','sintactico.py',72),
  ('transformacion -> empty','transformacion',1,'p_transformacion','sintactico.py',73),
  ('empty -> <empty>','empty',0,'p_empty','sintactico.py',76),
]
